# tell docker what version of the docker-compose.yml were using
version: '3'

# start the services section
services:
  # define the name of our service
  # corresponds to the "--name" parameter
  docker-nginx:
    restart: always
    build:
      context: ./nginx
    # defines the port mapping
    # corresponds to the "-p" flag
    ports:
      - "8081:80"
    tty: true
    volumes:
      - ./app/frontend:/var/www
      - ./app/backend:/var/app/backend
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - web-network

  docker-php-fpm:
    restart: always
    environment:
        XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1
    build: 
      context: ./php-fpm
    tty: true
    volumes:
      - ./app/frontend:/var/www
      - ./app/backend:/var/app/backend
    networks:
      - web-network

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3308:3306"
    volumes:
      #- ./db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - web-network
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    container_name: mysql


# define the network
networks:
  web-network:
volumes:
    data: